// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function FetchCompletion(arg1:string,arg2:spec.CompletionRequest,arg3:string):Promise<spec.CompletionResponse>;

export function Ping():Promise<string>;
