// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitManagers() {
  return window['go']['main']['App']['InitManagers']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}
