// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fileutil} from '../models';

export function OpenDirectoryWithFiles(arg1:number):Promise<fileutil.WalkDirectoryWithFilesResult>;

export function OpenFiles(arg1:boolean,arg2:Array<fileutil.FileFilter>):Promise<Array<fileutil.PathInfo>>;

export function Ping():Promise<string>;

export function SaveFile(arg1:string,arg2:string,arg3:Array<fileutil.FileFilter>):Promise<void>;
