// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectoryAsAttachments(arg1) {
  return window['go']['main']['App']['OpenDirectoryAsAttachments'](arg1);
}

export function OpenMultipleFilesAsAttachments(arg1, arg2) {
  return window['go']['main']['App']['OpenMultipleFilesAsAttachments'](arg1, arg2);
}

export function OpenURLAsAttachment(arg1) {
  return window['go']['main']['App']['OpenURLAsAttachment'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3);
}
