// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { spec } from '../models';

export function AddMessageToConversation(arg1:spec.AddMessageToConversationRequest):Promise<spec.AddMessageToConversationResponse>;

export function DeleteConversation(arg1:spec.DeleteConversationRequest):Promise<spec.DeleteConversationResponse>;

export function GetConversation(arg1:spec.GetConversationRequest):Promise<spec.GetConversationResponse>;

export function ListConversations(arg1:spec.ListConversationsRequest):Promise<spec.ListConversationsResponse>;

export function SearchConversations(arg1:spec.SearchConversationsRequest):Promise<spec.SearchConversationsResponse>;

export function SaveConversation(arg1:spec.SaveConversationRequest):Promise<spec.SaveConversationResponse>;

