// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMessageToConversation(arg1) {
  return window['go']['main']['ConversationCollectionWrapper']['AddMessageToConversation'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['ConversationCollectionWrapper']['DeleteConversation'](arg1);
}

export function GetConversation(arg1) {
  return window['go']['main']['ConversationCollectionWrapper']['GetConversation'](arg1);
}

export function ListConversations(arg1) {
  return window['go']['main']['ConversationCollectionWrapper']['ListConversations'](arg1);
}

export function PutConversation(arg1) {
  return window['go']['main']['ConversationCollectionWrapper']['PutConversation'](arg1);
}

export function SearchConversations(arg1) {
  return window['go']['main']['ConversationCollectionWrapper']['SearchConversations'](arg1);
}
