// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function AddModelPreset(arg1:spec.AddModelPresetRequest):Promise<spec.AddModelPresetResponse>;

export function CreateModelPresets(arg1:spec.CreateModelPresetsRequest):Promise<spec.CreateModelPresetsResponse>;

export function DeleteModelPreset(arg1:spec.DeleteModelPresetRequest):Promise<spec.DeleteModelPresetResponse>;

export function DeleteModelPresets(arg1:spec.DeleteModelPresetsRequest):Promise<spec.DeleteModelPresetsResponse>;

export function GetAllModelPresets(arg1:spec.GetAllModelPresetsRequest):Promise<spec.GetAllModelPresetsResponse>;
