// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddModelPreset(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['AddModelPreset'](arg1);
}

export function CreateProviderPreset(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['CreateProviderPreset'](arg1);
}

export function DeleteModelPreset(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['DeleteModelPreset'](arg1);
}

export function DeleteProviderPreset(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['DeleteProviderPreset'](arg1);
}

export function GetAllModelPresets(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['GetAllModelPresets'](arg1);
}

export function SetDefaultModelPreset(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['SetDefaultModelPreset'](arg1);
}
