// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteModelPreset(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['DeleteModelPreset'](arg1);
}

export function DeleteProviderPreset(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['DeleteProviderPreset'](arg1);
}

export function GetDefaultProvider(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['GetDefaultProvider'](arg1);
}

export function ListProviderPresets(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['ListProviderPresets'](arg1);
}

export function PatchDefaultProvider(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['PatchDefaultProvider'](arg1);
}

export function PatchModelPreset(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['PatchModelPreset'](arg1);
}

export function PatchProviderPreset(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['PatchProviderPreset'](arg1);
}

export function PutModelPreset(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['PutModelPreset'](arg1);
}

export function PutProviderPreset(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['PutProviderPreset'](arg1);
}
