// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function DeleteModelPreset(arg1:spec.DeleteModelPresetRequest):Promise<spec.DeleteModelPresetResponse>;

export function DeleteProviderPreset(arg1:spec.DeleteProviderPresetRequest):Promise<spec.DeleteProviderPresetResponse>;

export function ListProviderPresets(arg1:spec.ListProviderPresetsRequest):Promise<spec.ListProviderPresetsResponse>;

export function PatchModelPreset(arg1:spec.PatchModelPresetRequest):Promise<spec.PatchModelPresetResponse>;

export function PatchProviderPreset(arg1:spec.PatchProviderPresetRequest):Promise<spec.PatchProviderPresetResponse>;

export function PutModelPreset(arg1:spec.PutModelPresetRequest):Promise<spec.PutModelPresetResponse>;

export function PutProviderPreset(arg1:spec.PutProviderPresetRequest):Promise<spec.PutProviderPresetResponse>;
