// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddModelPreset(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['AddModelPreset'](arg1);
}

export function CreateModelPresets(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['CreateModelPresets'](arg1);
}

export function DeleteModelPreset(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['DeleteModelPreset'](arg1);
}

export function DeleteModelPresets(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['DeleteModelPresets'](arg1);
}

export function GetAllModelPresets(arg1) {
  return window['go']['main']['ModelPresetStoreWrapper']['GetAllModelPresets'](arg1);
}
