// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePromptBundle(arg1) {
  return window['go']['main']['PromptTemplateStoreWrapper']['DeletePromptBundle'](arg1);
}

export function DeletePromptTemplate(arg1) {
  return window['go']['main']['PromptTemplateStoreWrapper']['DeletePromptTemplate'](arg1);
}

export function GetPromptTemplate(arg1) {
  return window['go']['main']['PromptTemplateStoreWrapper']['GetPromptTemplate'](arg1);
}

export function ListPromptBundles(arg1) {
  return window['go']['main']['PromptTemplateStoreWrapper']['ListPromptBundles'](arg1);
}

export function ListPromptTemplates(arg1) {
  return window['go']['main']['PromptTemplateStoreWrapper']['ListPromptTemplates'](arg1);
}

export function PatchPromptBundle(arg1) {
  return window['go']['main']['PromptTemplateStoreWrapper']['PatchPromptBundle'](arg1);
}

export function PatchPromptTemplate(arg1) {
  return window['go']['main']['PromptTemplateStoreWrapper']['PatchPromptTemplate'](arg1);
}

export function PutPromptBundle(arg1) {
  return window['go']['main']['PromptTemplateStoreWrapper']['PutPromptBundle'](arg1);
}

export function PutPromptTemplate(arg1) {
  return window['go']['main']['PromptTemplateStoreWrapper']['PutPromptTemplate'](arg1);
}

export function SearchPromptTemplates(arg1) {
  return window['go']['main']['PromptTemplateStoreWrapper']['SearchPromptTemplates'](arg1);
}
