// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function DeletePromptBundle(arg1:spec.DeletePromptBundleRequest):Promise<spec.DeletePromptBundleResponse>;

export function DeletePromptTemplate(arg1:spec.DeletePromptTemplateRequest):Promise<spec.DeletePromptTemplateResponse>;

export function GetPromptTemplate(arg1:spec.GetPromptTemplateRequest):Promise<spec.GetPromptTemplateResponse>;

export function ListPromptBundles(arg1:spec.ListPromptBundlesRequest):Promise<spec.ListPromptBundlesResponse>;

export function ListPromptTemplates(arg1:spec.ListPromptTemplatesRequest):Promise<spec.ListPromptTemplatesResponse>;

export function PatchPromptBundle(arg1:spec.PatchPromptBundleRequest):Promise<spec.PatchPromptBundleResponse>;

export function PatchPromptTemplate(arg1:spec.PatchPromptTemplateRequest):Promise<spec.PatchPromptTemplateResponse>;

export function PutPromptBundle(arg1:spec.PutPromptBundleRequest):Promise<spec.PutPromptBundleResponse>;

export function PutPromptTemplate(arg1:spec.PutPromptTemplateRequest):Promise<spec.PutPromptTemplateResponse>;

export function SearchPromptTemplates(arg1:spec.SearchPromptTemplatesRequest):Promise<spec.SearchPromptTemplatesResponse>;
