// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProvider(arg1) {
  return window['go']['main']['ProviderSetWrapper']['AddProvider'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['ProviderSetWrapper']['DeleteProvider'](arg1);
}

export function FetchCompletion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['ProviderSetWrapper']['FetchCompletion'](arg1, arg2, arg3, arg4, arg5);
}

export function GetConfigurationInfo(arg1) {
  return window['go']['main']['ProviderSetWrapper']['GetConfigurationInfo'](arg1);
}

export function SetDefaultProvider(arg1) {
  return window['go']['main']['ProviderSetWrapper']['SetDefaultProvider'](arg1);
}

export function SetProviderAPIKey(arg1) {
  return window['go']['main']['ProviderSetWrapper']['SetProviderAPIKey'](arg1);
}

export function SetProviderAttribute(arg1) {
  return window['go']['main']['ProviderSetWrapper']['SetProviderAttribute'](arg1);
}
