// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllSettings(arg1) {
  return window['go']['main']['SettingStoreWrapper']['GetAllSettings'](arg1);
}

export function SetSetting(arg1) {
  return window['go']['main']['SettingStoreWrapper']['SetSetting'](arg1);
}
