// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAuthKey(arg1) {
  return window['go']['main']['SettingStoreWrapper']['DeleteAuthKey'](arg1);
}

export function GetAuthKey(arg1) {
  return window['go']['main']['SettingStoreWrapper']['GetAuthKey'](arg1);
}

export function GetSettings(arg1) {
  return window['go']['main']['SettingStoreWrapper']['GetSettings'](arg1);
}

export function SetAppTheme(arg1) {
  return window['go']['main']['SettingStoreWrapper']['SetAppTheme'](arg1);
}

export function SetAuthKey(arg1) {
  return window['go']['main']['SettingStoreWrapper']['SetAuthKey'](arg1);
}
