// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAISetting(arg1) {
  return window['go']['main']['SettingStoreWrapper']['AddAISetting'](arg1);
}

export function AddModelSetting(arg1) {
  return window['go']['main']['SettingStoreWrapper']['AddModelSetting'](arg1);
}

export function DeleteAISetting(arg1) {
  return window['go']['main']['SettingStoreWrapper']['DeleteAISetting'](arg1);
}

export function DeleteModelSetting(arg1) {
  return window['go']['main']['SettingStoreWrapper']['DeleteModelSetting'](arg1);
}

export function GetAllSettings(arg1) {
  return window['go']['main']['SettingStoreWrapper']['GetAllSettings'](arg1);
}

export function SetAISettingAPIKey(arg1) {
  return window['go']['main']['SettingStoreWrapper']['SetAISettingAPIKey'](arg1);
}

export function SetAISettingAttrs(arg1) {
  return window['go']['main']['SettingStoreWrapper']['SetAISettingAttrs'](arg1);
}

export function SetAppSettings(arg1) {
  return window['go']['main']['SettingStoreWrapper']['SetAppSettings'](arg1);
}
