// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settingstore} from '../models';

export function AddAISetting(arg1:settingstore.AddAISettingRequest):Promise<settingstore.AddAISettingResponse>;

export function DeleteAISetting(arg1:settingstore.DeleteAISettingRequest):Promise<settingstore.DeleteAISettingResponse>;

export function GetAllSettings(arg1:settingstore.GetAllSettingsRequest):Promise<settingstore.GetAllSettingsResponse>;

export function SetAISettingAPIKey(arg1:settingstore.SetAISettingAPIKeyRequest):Promise<settingstore.SetAISettingAPIKeyResponse>;

export function SetAISettingAttrs(arg1:settingstore.SetAISettingAttrsRequest):Promise<settingstore.SetAISettingAttrsResponse>;

export function SetAppSettings(arg1:settingstore.SetAppSettingsRequest):Promise<settingstore.SetAppSettingsResponse>;
