// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function AddAISetting(arg1:spec.AddAISettingRequest):Promise<spec.AddAISettingResponse>;

export function AddModelPreset(arg1:spec.AddModelPresetRequest):Promise<spec.AddModelPresetResponse>;

export function DeleteAISetting(arg1:spec.DeleteAISettingRequest):Promise<spec.DeleteAISettingResponse>;

export function DeleteModelPreset(arg1:spec.DeleteModelPresetRequest):Promise<spec.DeleteModelPresetResponse>;

export function GetAllSettings(arg1:spec.GetAllSettingsRequest):Promise<spec.GetAllSettingsResponse>;

export function SetAISettingAPIKey(arg1:spec.SetAISettingAPIKeyRequest):Promise<spec.SetAISettingAPIKeyResponse>;

export function SetAISettingAttrs(arg1:spec.SetAISettingAttrsRequest):Promise<spec.SetAISettingAttrsResponse>;

export function SetAppSettings(arg1:spec.SetAppSettingsRequest):Promise<spec.SetAppSettingsResponse>;
