// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function DeleteTool(arg1:spec.DeleteToolRequest):Promise<spec.DeleteToolResponse>;

export function DeleteToolBundle(arg1:spec.DeleteToolBundleRequest):Promise<spec.DeleteToolBundleResponse>;

export function GetTool(arg1:spec.GetToolRequest):Promise<spec.GetToolResponse>;

export function ListToolBundles(arg1:spec.ListToolBundlesRequest):Promise<spec.ListToolBundlesResponse>;

export function ListTools(arg1:spec.ListToolsRequest):Promise<spec.ListToolsResponse>;

export function PatchTool(arg1:spec.PatchToolRequest):Promise<spec.PatchToolResponse>;

export function PatchToolBundle(arg1:spec.PatchToolBundleRequest):Promise<spec.PatchToolBundleResponse>;

export function PutTool(arg1:spec.PutToolRequest):Promise<spec.PutToolResponse>;

export function PutToolBundle(arg1:spec.PutToolBundleRequest):Promise<spec.PutToolBundleResponse>;

export function SearchTools(arg1:spec.SearchToolsRequest):Promise<spec.SearchToolsResponse>;
