// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchCompletion(arg1, arg2, arg3) {
  return window['go']['wailsutils']['WrappedProviderSetAPI']['FetchCompletion'](arg1, arg2, arg3);
}

export function GetCompletionRequest(arg1, arg2, arg3, arg4) {
  return window['go']['wailsutils']['WrappedProviderSetAPI']['GetCompletionRequest'](arg1, arg2, arg3, arg4);
}

export function GetConfigurationInfo() {
  return window['go']['wailsutils']['WrappedProviderSetAPI']['GetConfigurationInfo']();
}

export function GetDefaultProvider() {
  return window['go']['wailsutils']['WrappedProviderSetAPI']['GetDefaultProvider']();
}

export function SetDefaultProvider(arg1) {
  return window['go']['wailsutils']['WrappedProviderSetAPI']['SetDefaultProvider'](arg1);
}

export function SetProviderAttribute(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsutils']['WrappedProviderSetAPI']['SetProviderAttribute'](arg1, arg2, arg3, arg4, arg5);
}
