package spec

import (
	"errors"
	"time"
)

const (
	ModelPresetsFile                     = "modelpresets.json" // Single JSON file.
	ModelPresetsBuiltInOverlayDBFileName = "modelpresetsbuiltin.overlay.sqlite"
)

const (
	SchemaVersion = "2025-07-01"

	MaxPageSize           = 256 // Max allowed page size.
	DefaultPageSize       = 256 // Default page size.
	BuiltInSnapshotMaxAge = time.Hour
)

const (
	DefaultAuthorizationHeaderKey = "Authorization"
	DefaultAPITimeout             = 300 * time.Second

	DefaultAnthropicOrigin                 = "https://api.anthropic.com"
	DefaultAnthropicChatCompletionPrefix   = "/v1/messages"
	DefaultAnthropicAuthorizationHeaderKey = "x-api-key"

	DefaultOpenAIOrigin                = "https://api.openai.com"
	DefaultOpenAIChatCompletionsPrefix = "/v1/chat/completions"
)

var OpenAIChatCompletionsDefaultHeaders = map[string]string{"content-type": "application/json"}

var (
	ErrInvalidDir = errors.New("invalid directory")

	ErrProviderNotFound      = errors.New("provider not found")
	ErrModelPresetNotFound   = errors.New("model preset not found")
	ErrBuiltInProviderAbsent = errors.New("provider not found in built-in data")

	ErrNilProvider      = errors.New("provider preset is nil")
	ErrNilModelPreset   = errors.New("model preset is nil")
	ErrNoModelPresets   = errors.New("provider has no model presets")
	ErrInvalidTimestamp = errors.New("zero timestamp")
	ErrBuiltInReadOnly  = errors.New("built-in resource is read-only")
)

type (
	ModelName        string
	ModelDisplayName string
	ModelSlug        string
	ModelPresetID    string
	ReasoningLevel   string
	ReasoningType    string

	ProviderName        string
	ProviderSDKType     string
	ProviderDisplayName string
)

const (
	ProviderSDKTypeAnthropic             ProviderSDKType = "providerSDKTypeAnthropic"
	ProviderSDKTypeOpenAIChatCompletions ProviderSDKType = "providerSDKTypeOpenAI"
	ProviderSDKTypeOpenAIResponses       ProviderSDKType = "providerSDKTypeOpenAIResponses"
)

const (
	ReasoningTypeHybridWithTokens ReasoningType = "hybridWithTokens"
	ReasoningTypeSingleWithLevels ReasoningType = "singleWithLevels"
)

const (
	ReasoningLevelNone    ReasoningLevel = "none"
	ReasoningLevelMinimal ReasoningLevel = "minimal"
	ReasoningLevelLow     ReasoningLevel = "low"
	ReasoningLevelMedium  ReasoningLevel = "medium"
	ReasoningLevelHigh    ReasoningLevel = "high"
	ReasoningLevelXHigh   ReasoningLevel = "xhigh"
)

type ReasoningParams struct {
	Type   ReasoningType  `json:"type"`
	Level  ReasoningLevel `json:"level"`
	Tokens int            `json:"tokens"`
}

type RoleEnum string

const (
	RoleSystem    RoleEnum = "system"
	RoleDeveloper RoleEnum = "developer"
	RoleUser      RoleEnum = "user"
	RoleAssistant RoleEnum = "assistant"
	RoleFunction  RoleEnum = "function"
	RoleTool      RoleEnum = "tool"
)

// Usage captures normalized token accounting across providers.
// If a provider does not expose a particular field, it will be 0.
type Usage struct {
	// Total input tokens for this request (cached + uncached).
	InputTokensTotal int64 `json:"inputTokensTotal"`

	// Input tokens that were served from or written to a cache (if the provider exposes this).
	InputTokensCached int64 `json:"inputTokensCached"`

	// Input tokens that were not cached.
	InputTokensUncached int64 `json:"inputTokensUncached"`

	// Output tokens generated by the model.
	OutputTokens int64 `json:"outputTokens"`

	// Tokens attributed to "reasoning" (if available).
	ReasoningTokens int64 `json:"reasoningTokens"`
}

type ReasoningContentType string

const (
	ReasoningContentTypeOpenAIResponses   ReasoningContentType = "reasoningOpenAIResponses"
	ReasoningContentTypeAnthropicMessages ReasoningContentType = "reasoningAnthropicMessages"
)

type ReasoningContentOpenAIResponses struct {
	ID      string   `json:"id"`
	Summary []string `json:"summary,omitzero"`
	Content []string `json:"content,omitzero"`
	Status  string   `json:"status,omitzero"`
	// The encrypted content of the reasoning item - populated when a response is
	// generated with `reasoning.encrypted_content` in the `include` parameter.
	EncryptedContent string `json:"encryptedContent,omitzero"`
}

type ReasoningContentAnthropicMessages struct {
	Signature        string `json:"signature"`
	Thinking         string `json:"thinking"`
	RedactedThinking string `json:"redactedThinking"`
}

type ReasoningContent struct {
	Type                     ReasoningContentType               `json:"type"`
	ContentOpenAIResponses   *ReasoningContentOpenAIResponses   `json:"contentOpenAIResponses,omitempty"`
	ContentAnthropicMessages *ReasoningContentAnthropicMessages `json:"contentAnthropicMessages,omitempty"`
}

// ModelPreset is the entire "model + default knobs" bundle the user can save.
// Anything not present in the preset is considered to be taken as default from any global or inbuilt model defaults.
type ModelPreset struct {
	SchemaVersion string           `json:"schemaVersion" required:"true"`
	ID            ModelPresetID    `json:"id"            required:"true"`
	Name          ModelName        `json:"name"          required:"true"`
	DisplayName   ModelDisplayName `json:"displayName"   required:"true"`
	Slug          ModelSlug        `json:"slug"          required:"true"`
	IsEnabled     bool             `json:"isEnabled"     required:"true"`

	Stream                      *bool            `json:"stream,omitempty"`
	MaxPromptLength             *int             `json:"maxPromptLength,omitempty"`
	MaxOutputLength             *int             `json:"maxOutputLength,omitempty"`
	Temperature                 *float64         `json:"temperature,omitempty"`
	Reasoning                   *ReasoningParams `json:"reasoning,omitempty"`
	SystemPrompt                *string          `json:"systemPrompt,omitempty"`
	Timeout                     *int             `json:"timeout,omitempty"`
	AdditionalParametersRawJSON *string          `json:"additionalParametersRawJSON,omitempty"`

	CreatedAt  time.Time `json:"createdAt"`
	ModifiedAt time.Time `json:"modifiedAt"`
	IsBuiltIn  bool      `json:"isBuiltIn"`
}

type ProviderPreset struct {
	SchemaVersion string              `json:"schemaVersion" required:"true"`
	Name          ProviderName        `json:"name"          required:"true"`
	DisplayName   ProviderDisplayName `json:"displayName"   required:"true"`
	SDKType       ProviderSDKType     `json:"sdkType"       required:"true"`
	IsEnabled     bool                `json:"isEnabled"     required:"true"`

	CreatedAt  time.Time `json:"createdAt"`
	ModifiedAt time.Time `json:"modifiedAt"`
	IsBuiltIn  bool      `json:"isBuiltIn"`

	Origin                   string            `json:"origin"                   required:"true"`
	ChatCompletionPathPrefix string            `json:"chatCompletionPathPrefix" required:"true"`
	APIKeyHeaderKey          string            `json:"apiKeyHeaderKey"          required:"true"`
	DefaultHeaders           map[string]string `json:"defaultHeaders"`

	DefaultModelPresetID ModelPresetID                 `json:"defaultModelPresetID"`
	ModelPresets         map[ModelPresetID]ModelPreset `json:"modelPresets"`
}

type PresetsSchema struct {
	SchemaVersion   string                          `json:"schemaVersion"`
	DefaultProvider ProviderName                    `json:"defaultProvider"`
	ProviderPresets map[ProviderName]ProviderPreset `json:"providerPresets"`
}
