name: Setup Tools
description: Sets up Go, Node, pnpm, Wails
inputs: {}
runs:
  using: "composite"
  steps:
    - name: Setup GoLang
      uses: actions/setup-go@v6
      with:
        go-version-file: "go.mod"

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: "package.json"
        cache: "pnpm"

    - name: Install pnpm dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Install Wails
      run: ${{ env.INSTALL_TOOL_WAILS }}
      shell: bash
