// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchCompletion(arg1, arg2, arg3) {
  return window['go']['main']['ProviderSetWrapper']['FetchCompletion'](arg1, arg2, arg3);
}

export function GetConfigurationInfo(arg1) {
  return window['go']['main']['ProviderSetWrapper']['GetConfigurationInfo'](arg1);
}

export function GetDefaultProvider(arg1) {
  return window['go']['main']['ProviderSetWrapper']['GetDefaultProvider'](arg1);
}

export function MakeCompletion(arg1) {
  return window['go']['main']['ProviderSetWrapper']['MakeCompletion'](arg1);
}

export function SetDefaultProvider(arg1) {
  return window['go']['main']['ProviderSetWrapper']['SetDefaultProvider'](arg1);
}

export function SetProviderAttribute(arg1) {
  return window['go']['main']['ProviderSetWrapper']['SetProviderAttribute'](arg1);
}
