// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function GetAllSettings(arg1:spec.GetAllSettingsRequest):Promise<spec.GetAllSettingsResponse>;

export function SetSetting(arg1:spec.SetSettingRequest):Promise<spec.SetSettingResponse>;
