// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMessageToConversation(arg1, arg2, arg3) {
  return window['go']['conversationstore']['ConversationCollection']['AddMessageToConversation'](arg1, arg2, arg3);
}

export function DeleteConversation(arg1, arg2) {
  return window['go']['conversationstore']['ConversationCollection']['DeleteConversation'](arg1, arg2);
}

export function GetConversation(arg1, arg2) {
  return window['go']['conversationstore']['ConversationCollection']['GetConversation'](arg1, arg2);
}

export function GetConversationFilename(arg1) {
  return window['go']['conversationstore']['ConversationCollection']['GetConversationFilename'](arg1);
}

export function ListConversations(arg1) {
  return window['go']['conversationstore']['ConversationCollection']['ListConversations'](arg1);
}

export function SaveConversation(arg1) {
  return window['go']['conversationstore']['ConversationCollection']['SaveConversation'](arg1);
}
