// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function AddMessageToConversation(arg1:string,arg2:string,arg3:spec.ConversationMessage):Promise<void>;

export function DeleteConversation(arg1:string,arg2:string):Promise<void>;

export function GetConversation(arg1:string,arg2:string):Promise<spec.Conversation>;

export function GetConversationFilename(arg1:spec.Conversation):Promise<string>;

export function ListConversations(arg1:string):Promise<spec.ListResponse>;

export function SaveConversation(arg1:spec.Conversation):Promise<void>;
