// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function GetAllSettings(arg1:boolean):Promise<spec.SettingsSchema>;

export function SetSetting(arg1:string,arg2:any):Promise<void>;
